server:
  port: 8080
  servlet:
    context-path: /girl
  tomcat:
    uri-encoding: UTF-8
cupSize: A

spring:
  profiles:
    active: dev
  mvc:
    view:
     prefix: /html/
     suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clientsystem
    username: root
    password: 1234
    show-sql: true
  application:
      name: spring-boot-redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.1.4
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空
    password:
    jedis:
       # 连接超时时间（毫秒）
      timeout: 20000
      pool:
         # 连接池最大连接数（使用负值表示没有限制）
        max-active: 9
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0















